### ISSUE TITLE
SetSpan() ends beyond length

### ISSUE THREAD

**Issue by babitakapoor112** [imnapo/react-native-cn-richtext-editor#81]
i am getting this error while removing value from the text input in the rich text editor
![Screenshot_1569239974](https://user-images.githubusercontent.com/45659052/65423942-ed6dd600-de27-11e9-9a06-a23aaabdd42a.png)
.

**Comment by jsamr** [comment]
@babitakapoor112 Which react-native version are you using? I bet this is an instance of those bugs:

- https://github.com/facebook/react-native/issues/25265
- https://github.com/facebook/react-native/issues/17236
- https://github.com/facebook/react-native/issues/18316

RN `Text` component is unfortunately very unreliable and plagued by this bug which has regressed a lot. I noticed however that `expo` version of react-native is much more stable, and does not have this bug.

**Comment by cinatic** [comment]
same for me RN 0.60.4

**Comment by EremenkoAndrey** [comment]
This error appears when I use PureComponent or shouldComponentUpdate

**Comment by edipkavvas** [comment]
Something broken after 0.60 upgrade on Android. Before 0.60, everything was working as expected on Android, but now when i change selection via inputRef.setNativeProps method during onSelectionChange and if my input text is formatted (with dots for example) it gets crash of setSpan ( x .. x ) beyonds length

**Comment by Anjy123** [comment]
Did anyone find any solution?

**Comment by samipshah100** [comment]
I am having the same issue

    "react-native-cn-richtext-editor": "^2.0.0-rc3",
    "expo": "~36.0.0",

**Comment by jsamr** [comment]
Fixed in https://github.com/facebook/react-native/commit/6ebd3b046e5b71130281f1a7dbe7220eff95d74a; will be shipped in RN 0.62

**Comment by govind1530** [comment]
"react-native": "0.62.1",
    "react-native-cn-richtext-editor": "^2.0.0-rc2"
issue still exists

**Comment by trinhvanminh2009** [comment]
How i fix this error:
1. Go to File CNTextInput.js in library
2. Remove line  selection = {selection} in render Text input
