### ISSUE TITLE
In Android (RN 0.60.0 or above) issues

### ISSUE THREAD

**Issue by danyleo** [imnapo/react-native-cn-richtext-editor#89]
In Android (RN 0.60.0 or above) the editor blinks and hangs due to multiple calls of setStates and specially cursor issue, the cursor most of the times stands at wrong position

**Comment by mqtik** [comment]
This happens with the release bundle as well?

**Comment by danyleo** [comment]
yes with release also there is blink and cursor position issue, 
Test environment (RN 0,60.5,  Android 8.1, "react-native-cn-richtext-editor": "^1.0.42",) 
 Along with this there i s another issue when delete the letters it shows this error

![Screenshot_1573028799](https://user-images.githubusercontent.com/24935151/68282686-e5968800-009b-11ea-8313-ce537aa387c5.png)

**Comment by imnapo** [comment]
Hi @danyleo and @mqtik. This issue is related to react-native `TextInput` and it's `Selection` property (RN 0.60.0 or above). 
As you may know we are using TextInput and javascript array to load content in the editor. There are few major issues recently related to this. So we decided to design a new editor in this package and use `webview` and `html` instead of `TextInput`. 
I'm working on PR right now. I'm trying to implement this new editor with same features. It's almost ready. It should fix issues like this and also #86 and #88.

**Comment by mqtik** [comment]
Oh, I'll stay tuned to see that!
If you need help with something, just let me know @imnapo 

:D

**Comment by mqtik** [comment]
I think #86 it's fixed with the PR #87 

(I was also having the same problems)

**Comment by imnapo** [comment]
Yeah you're right :)

**Comment by muraterd** [comment]
I'm still having the same problem.

react-native: 0.61.4
react: 16.9.0"
react-native-cn-richtext-editor: ^1.0.42

**Comment by mqtik** [comment]
@muraterd 1.0.42, try **next** branch.

(npm install react-native-cn-richtext-editor@next)

**Comment by TheEarlyNerd** [comment]
@imnapo Thanks for your help, I tried the @next branch and the cursor is now synced properly. 

I noticed that the text still loads extremely slowly. I'm new to react native so it may be on my side, but I'm using the react native debugger and I don't see any performance issues with my simulator and I'm only running the example code for the advanced Rich Text Editor.

Is the slow typing something you are already aware of? If not, what do I need to do to demonstrate the problem on my Expo simulator? Thanks in advance!

**Comment by AndyRC6** [comment]
@mqtik Next branch did not work for me. I'm on RN version 0.61.4. The cursor flicker seems to have gotten worse actually. I'm also still getting the setSpan error shown above on Android. Any other fixes?

**Comment by shailesh92** [comment]
cursor flickering isssue  please tell me how to fixed it using cn-richtext-editor
